version: "3.1"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # MYSQL_USER: xxx
      # MYSQL_PASSWORD: xxx
      MYSQL_ROOT_PASSWORD: xxx
    volumes:
      - ./mysql/data:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
