services:
  postgres:
    image: postgres
    restart: always

    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tripdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db_network

  cloudbeaver:
    restart: unless-stopped
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:25.1.0
    ports:
      - 8978:8978
    environment:
      - CLOUDBEAVER_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/tripdata
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - db_network

volumes:
  postgres_data:
    driver: local

networks:
  db_network:
    driver: bridge
    name: db_network
